services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ngit-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=$mongodb+srv://dorusgame_db_user:on5oIB0CR2PXErZh@cluster0.q1y4bfd.mongodb.net/ngit_db?retryWrites=true&w=majority&appName=Cluster0
      - MONGODB_URI=${MONGODB_URI}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - RAZORPAY_KEY_ID=${RAZORPAY_KEY_ID}
      - RAZORPAY_KEY_SECRET=${RAZORPAY_KEY_SECRET}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
    env_file:
      - .env.production
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
